### ISSUE TITLE
Consider COBS framing

### ISSUE THREAD

**Issue by teohhanhui** [automerge/spanreed#23]
https://en.wikipedia.org/wiki/Consistent_Overhead_Byte_Stuffing

A good implementation seems to be https://docs.rs/corncobs/latest/corncobs/ (I've tried https://docs.rs/cobs/latest/cobs/ but it seems to have some known bugs...)

**Comment by alexjg** [comment]
My feeling is that this doesn't make sense as a built in feature of this library. The sync protocol already requires a reliable in-order channel (which in practice is TCP) so the self-synchronizing nature of COBS seems less useful whilst on the flip side length-prefixed CBOR is much easier to implement (for platforms without a library such as this one). Are there any major advantages to COBS that I'm not thinking of?

I am also working on exposing a generic method like this:

 ```
 RepoHandle::connect_stream<S, E>(&self, stream: S, direction: ConnDirection) 
 where
     S: Stream<Result<Message, E>> + Sink<Result<Message, E>>
     E: std::error::Error
```

Which would allow users to implement whatever framing they like so we're not constraining people to the length prefixed CBOR, we're just defaulting to that.
