### ISSUE TITLE
Consider `Arc<RwLock<Doc>>` instead of `Arc<Mutex<Doc>>`

### ISSUE THREAD

**Issue by teohhanhui** [automerge/spanreed#24]
In the implementation of our ORM layer on top of `autoserde`, we're using `Arc<RwLock<Doc>>` to support multiple concurrent readers.

I wonder if it'd be appropriate for this crate?

**Comment by alexjg** [comment]
This is implemented in #20 which I think we will merge shortly

**Comment by gterzian** [comment]
Done in https://github.com/automerge/spanreed/pull/20
